// Generated by Kinetrix Compiler (Target: ESP32)
// Board: ESP32 Dev Module
// Upload via: Arduino IDE with ESP32 board package

#include <Arduino.h>

#include <WiFi.h>
#include <ArduinoOTA.h>
#include <esp_now.h>
#include <esp_task_wdt.h>
#include <esp32-hal-ledc.h>
#include <ESP32Servo.h>
#include <DHT.h>
#include <Adafruit_NeoPixel.h>
#include <LiquidCrystal_I2C.h>
#include <Stepper.h>
#include <Encoder.h>
#include <PID_v1.h>

/* ESP32-specific declarations */
Servo _kx_servo;

DHT *_kx_dht = NULL;

Adafruit_NeoPixel *_kx_strip = NULL;

LiquidCrystal_I2C *_kx_lcd = NULL;

Stepper *_kx_stepper = NULL;

int _kx_motor_en = -1, _kx_motor_fwd = -1, _kx_motor_rev = -1;

Encoder *_kx_encoder = NULL;

Servo _kx_esc;

double _kx_pid_setpoint = 0, _kx_pid_input = 0, _kx_pid_output = 0;

PID *_kx_pid = NULL;

int _esp32_pwm_channels[40] = {0};
int _esp32_next_pwm_channel = 0;
void _ledc_analogWrite(uint8_t pin, int value) {
  if (_esp32_pwm_channels[pin] == 0) {
    _esp32_pwm_channels[pin] = _esp32_next_pwm_channel + 1;
    ledcSetup(_esp32_next_pwm_channel, 5000, 8); // 5kHz, 8-bit
    ledcAttachPin(pin, _esp32_next_pwm_channel);
    _esp32_next_pwm_channel++;
  }
  ledcWrite(_esp32_pwm_channels[pin] - 1, value);
}

/* ESP-NOW state */
volatile float _esp_now_last_val = 0.0;
volatile bool _esp_now_has_data = false;
void _esp_now_recv_cb(const uint8_t *mac_addr, const uint8_t *data, int data_len) {
  if (data_len == sizeof(float)) {
    memcpy((void*)&_esp_now_last_val, data, sizeof(float));
    _esp_now_has_data = true;
  }
}
void radio_send_peer(int peer_id, float value) {
  uint8_t mac_addr[6] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};
  esp_now_peer_info_t peerInfo = {};
  memcpy(peerInfo.peer_addr, mac_addr, 6);
  peerInfo.channel = 0;
  peerInfo.encrypt = false;
  if (!esp_now_is_peer_exist(mac_addr)) esp_now_add_peer(&peerInfo);
  esp_now_send(mac_addr, (uint8_t*)&value, sizeof(float));
}
float radio_read() {
  _esp_now_has_data = false;
  return _esp_now_last_val;
}
bool radio_available() {
  return _esp_now_has_data;
}

void setup() {
  Serial.begin(115200);  // ESP32 default baud
  analogReadResolution(12);  // ESP32 12-bit ADC (0-4095)
  WiFi.mode(WIFI_STA);
  esp_now_init();
  esp_now_register_recv_cb(_esp_now_recv_cb);
}

void loop() {
  _kx_stepper = new Stepper(200, 5, 6);
  _kx_motor_en = 9;
  _kx_motor_fwd = 10;
  _kx_motor_rev = 11;
  pinMode(_kx_motor_en, OUTPUT);

  pinMode(_kx_motor_fwd, OUTPUT);

  pinMode(_kx_motor_rev, OUTPUT);

  _kx_encoder = new Encoder(2, 3);
  _kx_esc.attach(4, 1000, 2000);
  if (_kx_pid) delete _kx_pid;
  _kx_pid = new PID(&_kx_pid_input, &_kx_pid_output, &_kx_pid_setpoint, 2, 0.5, 1.2, DIRECT);
  if (_kx_pid) _kx_pid->SetMode(AUTOMATIC);

  if (_kx_stepper) _kx_stepper->step(200);
  if (_kx_stepper) _kx_stepper->setSpeed(120);
  if (_kx_motor_en != -1) {

    digitalWrite(_kx_motor_fwd, HIGH);

    digitalWrite(_kx_motor_rev, LOW);

    _ledc_analogWrite(_kx_motor_en, 255);
  }

  delay(1000);
  if (_kx_motor_en != -1) {

    digitalWrite(_kx_motor_fwd, LOW);

    digitalWrite(_kx_motor_rev, HIGH);

    _ledc_analogWrite(_kx_motor_en, 128);
  }

  delay(1000);
  if (_kx_motor_en != -1) {

    digitalWrite(_kx_motor_fwd, LOW);

    digitalWrite(_kx_motor_rev, LOW);

    _ledc_analogWrite(_kx_motor_en, 0);

  }

  _kx_esc.write(90);
  _kx_pid_setpoint = 100;
  for (int _i0 = 0; _i0 < (int)(
10); _i0++) {
    pos = 0 /* unsupported expr */;
    out = 0 /* unsupported expr */;
    if (
(out > 0)) {
      if (_kx_motor_en != -1) {

        digitalWrite(_kx_motor_fwd, HIGH);

        digitalWrite(_kx_motor_rev, LOW);

        _ledc_analogWrite(_kx_motor_en, out);
      }

    }
 else {
      if (_kx_motor_en != -1) {

        digitalWrite(_kx_motor_fwd, LOW);

        digitalWrite(_kx_motor_rev, HIGH);

        _ledc_analogWrite(_kx_motor_en, (out * (0 - 1)));
      }

    }

    delay(100);
  }

  if (_kx_encoder) _kx_encoder->write(0);

}
